// Code generated by protoc-gen-go.
// source: action_type.proto
// DO NOT EDIT!

/*
Package PekkaService is a generated protocol buffer package.

It is generated from these files:
	action_type.proto
	button.proto
	event_timer.proto
	executor.proto
	executor_action.proto
	pekka_service.proto
	pentti.proto
	weekly_timer.proto

It has these top-level messages:
	Button
	EditButtonRequest
	EditButtonResponse
	EventTimer
	Executor
	FetchExecutorsRequest
	FetchExecutorByIdRequest
	FetchExecutorByIdResponse
	FetchExecutorActionsByExecutorIdRequest
	CreateExecutorRequest
	CreateExecutorResponse
	ExecutorAction
	AddExecutorActionToExecutorRequest
	AddExecutorActionToExecutorResponse
	Pentti
	FetchPenttiDevicesRequest
	FetchPenttiByIdRequest
	FetchPenttiByIdResponse
	FetchButtonsByPenttiIdRequest
	WeeklyTimer
	FetchWeeklyTimersRequest
	FetchWeeklyTimerByIdRequest
	FetchWeeklyTimerByIdResponse
	FetchWeeklyTimerBySlugRequest
	FetchWeeklyTimerBySlugResponse
	CreateWeeklyTimerRequest
	CreateWeeklyTimerResponse
	EditWeeklyTimerRequest
	EditWeeklyTimerResponse
*/
package PekkaService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ActionType int32

const (
	ActionType_MATRIX_CONNECTION ActionType = 0
)

var ActionType_name = map[int32]string{
	0: "MATRIX_CONNECTION",
}
var ActionType_value = map[string]int32{
	"MATRIX_CONNECTION": 0,
}

func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}
func (ActionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("PekkaService.ActionType", ActionType_name, ActionType_value)
}

func init() { proto.RegisterFile("action_type.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 96 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x4c, 0x2e, 0xc9,
	0xcc, 0xcf, 0x8b, 0x2f, 0xa9, 0x2c, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x09,
	0x48, 0xcd, 0xce, 0x4e, 0x0c, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x52, 0xe6, 0xe2, 0x72,
	0x04, 0x2b, 0x09, 0xa9, 0x2c, 0x48, 0x15, 0x12, 0xe5, 0x12, 0xf4, 0x75, 0x0c, 0x09, 0xf2, 0x8c,
	0x88, 0x77, 0xf6, 0xf7, 0xf3, 0x73, 0x75, 0x0e, 0xf1, 0xf4, 0xf7, 0x13, 0x60, 0x48, 0x62, 0x03,
	0xeb, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x09, 0x7e, 0xfa, 0x4e, 0x00, 0x00, 0x00,
}
