// Code generated by protoc-gen-go.
// source: button.proto
// DO NOT EDIT!

/*
Package PekkaService is a generated protocol buffer package.

It is generated from these files:
	button.proto
	event_timer.proto
	executor.proto
	executor_action.proto
	pekka_service.proto
	pentti.proto
	weekly_timer.proto

It has these top-level messages:
	Button
	EventTimer
	Executor
	ExecutorAction
	Pentti
	WeeklyTimer
	FetchWeeklyTimersRequest
	FetchWeeklyTimerByIdRequest
	FetchWeeklyTimerByIdResponse
	FetchWeeklyTimerBySlugRequest
	FetchWeeklyTimerBySlugResponse
*/
package PekkaService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Button struct {
}

func (m *Button) Reset()                    { *m = Button{} }
func (m *Button) String() string            { return proto.CompactTextString(m) }
func (*Button) ProtoMessage()               {}
func (*Button) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Button)(nil), "PekkaService.Button")
}

func init() { proto.RegisterFile("button.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 64 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2a, 0x2d, 0x29,
	0xc9, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x09, 0x48, 0xcd, 0xce, 0x4e, 0x0c,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x55, 0xe2, 0xe0, 0x62, 0x73, 0x02, 0xcb, 0x26, 0xb1, 0x81,
	0xa5, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x4b, 0x5d, 0x90, 0x2e, 0x00, 0x00, 0x00,
}
