// Code generated by protoc-gen-go.
// source: weekly_timer.proto
// DO NOT EDIT!

package PekkaService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type WeeklyTimer struct {
	Id        uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Slug      string `protobuf:"bytes,2,opt,name=slug" json:"slug,omitempty"`
	Minutes   uint32 `protobuf:"varint,3,opt,name=minutes" json:"minutes,omitempty"`
	Hours     uint32 `protobuf:"varint,4,opt,name=hours" json:"hours,omitempty"`
	Active    bool   `protobuf:"varint,5,opt,name=active" json:"active,omitempty"`
	Monday    bool   `protobuf:"varint,6,opt,name=monday" json:"monday,omitempty"`
	Tuesday   bool   `protobuf:"varint,7,opt,name=tuesday" json:"tuesday,omitempty"`
	Wednesday bool   `protobuf:"varint,8,opt,name=wednesday" json:"wednesday,omitempty"`
	Thursday  bool   `protobuf:"varint,9,opt,name=thursday" json:"thursday,omitempty"`
	Friday    bool   `protobuf:"varint,10,opt,name=friday" json:"friday,omitempty"`
	Saturday  bool   `protobuf:"varint,11,opt,name=saturday" json:"saturday,omitempty"`
	Sunday    bool   `protobuf:"varint,12,opt,name=sunday" json:"sunday,omitempty"`
}

func (m *WeeklyTimer) Reset()                    { *m = WeeklyTimer{} }
func (m *WeeklyTimer) String() string            { return proto.CompactTextString(m) }
func (*WeeklyTimer) ProtoMessage()               {}
func (*WeeklyTimer) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *WeeklyTimer) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WeeklyTimer) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *WeeklyTimer) GetMinutes() uint32 {
	if m != nil {
		return m.Minutes
	}
	return 0
}

func (m *WeeklyTimer) GetHours() uint32 {
	if m != nil {
		return m.Hours
	}
	return 0
}

func (m *WeeklyTimer) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *WeeklyTimer) GetMonday() bool {
	if m != nil {
		return m.Monday
	}
	return false
}

func (m *WeeklyTimer) GetTuesday() bool {
	if m != nil {
		return m.Tuesday
	}
	return false
}

func (m *WeeklyTimer) GetWednesday() bool {
	if m != nil {
		return m.Wednesday
	}
	return false
}

func (m *WeeklyTimer) GetThursday() bool {
	if m != nil {
		return m.Thursday
	}
	return false
}

func (m *WeeklyTimer) GetFriday() bool {
	if m != nil {
		return m.Friday
	}
	return false
}

func (m *WeeklyTimer) GetSaturday() bool {
	if m != nil {
		return m.Saturday
	}
	return false
}

func (m *WeeklyTimer) GetSunday() bool {
	if m != nil {
		return m.Sunday
	}
	return false
}

type FetchWeeklyTimersRequest struct {
	Offset uint32 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Limit  uint32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *FetchWeeklyTimersRequest) Reset()                    { *m = FetchWeeklyTimersRequest{} }
func (m *FetchWeeklyTimersRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchWeeklyTimersRequest) ProtoMessage()               {}
func (*FetchWeeklyTimersRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *FetchWeeklyTimersRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FetchWeeklyTimersRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type FetchWeeklyTimerByIdRequest struct {
	WeeklyTimerId uint32 `protobuf:"varint,1,opt,name=weeklyTimerId" json:"weeklyTimerId,omitempty"`
}

func (m *FetchWeeklyTimerByIdRequest) Reset()                    { *m = FetchWeeklyTimerByIdRequest{} }
func (m *FetchWeeklyTimerByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchWeeklyTimerByIdRequest) ProtoMessage()               {}
func (*FetchWeeklyTimerByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *FetchWeeklyTimerByIdRequest) GetWeeklyTimerId() uint32 {
	if m != nil {
		return m.WeeklyTimerId
	}
	return 0
}

type FetchWeeklyTimerByIdResponse struct {
	WeeklyTimer *WeeklyTimer `protobuf:"bytes,1,opt,name=weeklyTimer" json:"weeklyTimer,omitempty"`
}

func (m *FetchWeeklyTimerByIdResponse) Reset()                    { *m = FetchWeeklyTimerByIdResponse{} }
func (m *FetchWeeklyTimerByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchWeeklyTimerByIdResponse) ProtoMessage()               {}
func (*FetchWeeklyTimerByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *FetchWeeklyTimerByIdResponse) GetWeeklyTimer() *WeeklyTimer {
	if m != nil {
		return m.WeeklyTimer
	}
	return nil
}

type FetchWeeklyTimerBySlugRequest struct {
	WeeklyTimerSlug string `protobuf:"bytes,1,opt,name=weeklyTimerSlug" json:"weeklyTimerSlug,omitempty"`
}

func (m *FetchWeeklyTimerBySlugRequest) Reset()                    { *m = FetchWeeklyTimerBySlugRequest{} }
func (m *FetchWeeklyTimerBySlugRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchWeeklyTimerBySlugRequest) ProtoMessage()               {}
func (*FetchWeeklyTimerBySlugRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *FetchWeeklyTimerBySlugRequest) GetWeeklyTimerSlug() string {
	if m != nil {
		return m.WeeklyTimerSlug
	}
	return ""
}

type FetchWeeklyTimerBySlugResponse struct {
	WeeklyTimer *WeeklyTimer `protobuf:"bytes,1,opt,name=weeklyTimer" json:"weeklyTimer,omitempty"`
}

func (m *FetchWeeklyTimerBySlugResponse) Reset()                    { *m = FetchWeeklyTimerBySlugResponse{} }
func (m *FetchWeeklyTimerBySlugResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchWeeklyTimerBySlugResponse) ProtoMessage()               {}
func (*FetchWeeklyTimerBySlugResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

func (m *FetchWeeklyTimerBySlugResponse) GetWeeklyTimer() *WeeklyTimer {
	if m != nil {
		return m.WeeklyTimer
	}
	return nil
}

func init() {
	proto.RegisterType((*WeeklyTimer)(nil), "PekkaService.WeeklyTimer")
	proto.RegisterType((*FetchWeeklyTimersRequest)(nil), "PekkaService.FetchWeeklyTimersRequest")
	proto.RegisterType((*FetchWeeklyTimerByIdRequest)(nil), "PekkaService.FetchWeeklyTimerByIdRequest")
	proto.RegisterType((*FetchWeeklyTimerByIdResponse)(nil), "PekkaService.FetchWeeklyTimerByIdResponse")
	proto.RegisterType((*FetchWeeklyTimerBySlugRequest)(nil), "PekkaService.FetchWeeklyTimerBySlugRequest")
	proto.RegisterType((*FetchWeeklyTimerBySlugResponse)(nil), "PekkaService.FetchWeeklyTimerBySlugResponse")
}

func init() { proto.RegisterFile("weekly_timer.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcd, 0x4b, 0xeb, 0x40,
	0x14, 0xc5, 0x49, 0x5e, 0xbf, 0x72, 0xd3, 0xbe, 0x07, 0xc3, 0x43, 0x46, 0xad, 0x52, 0x82, 0x8b,
	0xac, 0xba, 0xd0, 0xa5, 0x3b, 0x05, 0xb1, 0x3b, 0x99, 0x0a, 0x2e, 0x44, 0x24, 0x36, 0xb7, 0xed,
	0xd0, 0x7c, 0xd4, 0xf9, 0x68, 0xe9, 0x9f, 0xe5, 0x7f, 0x28, 0x33, 0xd3, 0xd8, 0x58, 0x75, 0xe7,
	0x2e, 0xbf, 0x73, 0xee, 0x39, 0x33, 0xdc, 0x0c, 0x90, 0x35, 0xe2, 0x22, 0xdb, 0x3c, 0x2b, 0x9e,
	0xa3, 0x18, 0x2e, 0x45, 0xa9, 0x4a, 0xd2, 0xbd, 0xc3, 0xc5, 0x22, 0x19, 0xa3, 0x58, 0xf1, 0x09,
	0x46, 0x6f, 0x3e, 0x84, 0x0f, 0x76, 0xe8, 0xde, 0xcc, 0x90, 0xbf, 0xe0, 0xf3, 0x94, 0x7a, 0x03,
	0x2f, 0xee, 0x31, 0x9f, 0xa7, 0x84, 0x40, 0x43, 0x66, 0x7a, 0x46, 0xfd, 0x81, 0x17, 0x07, 0xcc,
	0x7e, 0x13, 0x0a, 0xed, 0x9c, 0x17, 0x5a, 0xa1, 0xa4, 0x7f, 0xec, 0x60, 0x85, 0xe4, 0x3f, 0x34,
	0xe7, 0xa5, 0x16, 0x92, 0x36, 0xac, 0xee, 0x80, 0x1c, 0x40, 0x2b, 0x99, 0x28, 0xbe, 0x42, 0xda,
	0x1c, 0x78, 0x71, 0x87, 0x6d, 0xc9, 0xe8, 0x79, 0x59, 0xa4, 0xc9, 0x86, 0xb6, 0x9c, 0xee, 0xc8,
	0xf4, 0x2b, 0x8d, 0xd2, 0x18, 0x6d, 0x6b, 0x54, 0x48, 0xfa, 0x10, 0xac, 0x31, 0x2d, 0x9c, 0xd7,
	0xb1, 0xde, 0x4e, 0x20, 0x47, 0xd0, 0x51, 0x73, 0x2d, 0xac, 0x19, 0x58, 0xf3, 0x83, 0xcd, 0x59,
	0x53, 0xc1, 0x8d, 0x03, 0xee, 0x2c, 0x47, 0x26, 0x23, 0x13, 0xa5, 0x85, 0x71, 0x42, 0x97, 0xa9,
	0xd8, 0x64, 0xa4, 0xb6, 0xf7, 0xeb, 0xba, 0x8c, 0xa3, 0xe8, 0x16, 0xe8, 0x0d, 0xaa, 0xc9, 0xbc,
	0xb6, 0x37, 0xc9, 0xf0, 0x55, 0xa3, 0x54, 0x26, 0x53, 0x4e, 0xa7, 0x12, 0xd5, 0x76, 0x87, 0x5b,
	0x32, 0x9b, 0xc9, 0x78, 0xce, 0x95, 0x5d, 0x64, 0x8f, 0x39, 0x88, 0xae, 0xe1, 0x78, 0xbf, 0xe9,
	0x6a, 0x33, 0x4a, 0xab, 0xb2, 0x33, 0xe8, 0xad, 0x77, 0xce, 0xa8, 0xfa, 0x2f, 0x9f, 0xc5, 0xe8,
	0x11, 0xfa, 0xdf, 0x97, 0xc8, 0x65, 0x59, 0x48, 0x24, 0x97, 0x10, 0xd6, 0x02, 0xb6, 0x23, 0x3c,
	0x3f, 0x1c, 0xd6, 0x9f, 0xc1, 0xb0, 0x96, 0x65, 0xf5, 0xe9, 0x68, 0x04, 0x27, 0x5f, 0xcb, 0xc7,
	0x99, 0x9e, 0x55, 0x77, 0x8c, 0xe1, 0x5f, 0x6d, 0xde, 0x38, 0xf6, 0x84, 0x80, 0xed, 0xcb, 0xd1,
	0x13, 0x9c, 0xfe, 0x54, 0xf5, 0x0b, 0x37, 0x7d, 0x69, 0xd9, 0xe7, 0x7d, 0xf1, 0x1e, 0x00, 0x00,
	0xff, 0xff, 0xf3, 0xbb, 0x39, 0xf9, 0xf4, 0x02, 0x00, 0x00,
}
